package ensigncycle

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strings"
	"testing"

	statuspkg "github.com/spacedock-dev/spacedock/internal/status"
)

func encodeProjectDir(cwd string) string {
	return strings.Map(func(r rune) rune {
		switch r {
		case '/', '.', '_':
			return '-'
		default:
			return r
		}
	}, cwd)
}

func seedStoredLoginCredential(configDir string) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("stored-login seed is macOS-keychain only (GOOS=%s)", runtime.GOOS)
	}
	raw, err := exec.Command("security", "find-generic-password", "-s", "Claude Code-credentials", "-w").Output()
	if err != nil {
		return fmt.Errorf("read keychain credential: %w", err)
	}
	credential := strings.TrimSpace(string(raw))
	var probe struct {
		ClaudeAIOauth json.RawMessage `json:"claudeAiOauth"`
	}
	if credential == "" || json.Unmarshal([]byte(credential), &probe) != nil || len(probe.ClaudeAIOauth) == 0 {
		return fmt.Errorf("keychain credential is empty or not the {claudeAiOauth:{...}} shape")
	}
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(configDir, ".credentials.json"), []byte(credential), 0o600)
}

func shellQuote(s string) string {
	if s != "" && !strings.ContainsAny(s, " \t\n'\"\\$`*?[]{}()&;|<>~#") {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

var nestedSessionMarkers = []string{
	"CLAUDECODE",
	"CLAUDE_CODE_CHILD_SESSION",
	"CLAUDE_CODE_SESSION_ID",
	"CLAUDE_CODE_AGENT",
	"CLAUDE_CODE_ENTRYPOINT",
	"CLAUDE_CODE_EXECPATH",
}

func unsetNestedSessionArgs(cmd ...string) []string {
	args := make([]string, 0, len(nestedSessionMarkers)*2+len(cmd))
	for _, marker := range nestedSessionMarkers {
		args = append(args, "-u", marker)
	}
	return append(args, cmd...)
}

func TestUnsetNestedSessionArgs(t *testing.T) {
	got := unsetNestedSessionArgs("spacedock", "claude", "--model", "sonnet")
	joined := strings.Join(got, " ")
	for _, marker := range nestedSessionMarkers {
		if !strings.Contains(joined, "-u "+marker) {
			t.Errorf("nested-session marker %q is not unset; args: %v", marker, got)
		}
	}
	wantTail := []string{"spacedock", "claude", "--model", "sonnet"}
	gotTail := got[len(got)-len(wantTail):]
	for i := range wantTail {
		if gotTail[i] != wantTail[i] {
			t.Errorf("launch command tail[%d] = %q, want %q (full: %v)", i, gotTail[i], wantTail[i], got)
		}
	}
}

func assertRecordedGateHoldLog(log string) error {
	const prepareToken = "exit=0\tgate prepare recorded-gate-task "
	prepare := strings.Index(log, prepareToken)
	commit := strings.LastIndex(log, "exit=0\tstate commit recorded-gate-task")
	head := strings.LastIndex(log, "state-head\t")
	const boundary = "gate hold crossed its committed no-authority boundary: "
	switch {
	case prepare < 0:
		return errGraded(boundary + "no successful gate prepare recorded")
	case commit < prepare:
		return errGraded(boundary + "state commit missing or before the successful gate prepare")
	case head < commit:
		return errGraded(boundary + "state-head missing or before the state commit")
	case strings.Count(log, prepareToken) != 1:
		return errGraded(boundary + "more than one successful gate prepare recorded")
	case strings.Contains(log[prepare:], " --decision "):
		return errGraded(boundary + "a decision was recorded after prepare")
	case strings.Contains(log[prepare:], "gate consume recorded-gate-task"):
		return errGraded(boundary + "the gate was consumed after prepare")
	case strings.Contains(log[prepare:], "dispatch build "):
		return errGraded(boundary + "a successor was dispatched after prepare")
	case strings.Contains(log[prepare:], "gate withdraw "):
		return errGraded(boundary + "the gate was withdrawn after prepare")
	case successfulStatusSet(log[prepare:]):
		return errGraded(boundary + "status changed after prepare")
	}
	return nil
}

func assertImplementationWorkerLifecycle(stream, entity string) error {
	return assertWorkerLifecycle(stream, entity, "implementation", "status=validation")
}

// claudeDispatchPointer matches the dispatch pointer the FO passes to a spawned
// worker. `spacedock dispatch build` generates the filename, so its trailing
// `-{stage}.md` is fixed by the dispatch contract rather than by FO phrasing.
var claudeDispatchPointer = regexp.MustCompile(`/spacedock-dispatch/[^\s"'` + "`" + `]*-([a-z0-9-]+)\.md`)

// claudeSpawnIsForStage decides whether an Agent spawn belongs to stage.
//
// The description is free text the FO composes, so matching on it alone is a
// false-negative machine: a live FO dispatched its validator as "Validate
// auto-continue-task implementation" and its re-validator as "Re-validate
// auto-continue-task cycle 2", and neither contains the noun "validation", so a
// three-agent run counted zero. The prompt's dispatch pointer is generated by
// `spacedock dispatch build` and names the stage exactly, so it recognises those
// spawns while still excluding the reviser, whose pointer ends `-implementation.md`.
//
// Both signals are kept: the description check preserves every spawn the matcher
// already counted, and the pointer only adds spawns the contract itself labels.
//
// The description check reads the stage as a WHOLE TOKEN rather than as a bare
// substring (audit finding 10). The two repairs pull in opposite directions and
// both are needed: the pointer fixes the false NEGATIVE this comment describes,
// and the token anchor fixes the false POSITIVE the substring produced, where text
// merely CONTAINING the letters counted as a dispatch of that stage. Anchoring does
// not narrow the case above — "Validate auto-continue-task implementation" never
// contained the noun "validation" to begin with, so the pointer is what recognises
// it either way.
func claudeSpawnIsForStage(description, prompt, stage string) bool {
	if stageToken(description, stage) {
		return true
	}
	for _, m := range claudeDispatchPointer.FindAllStringSubmatch(prompt, -1) {
		if m[1] == stage {
			return true
		}
	}
	return false
}

func assertWorkerLifecycle(stream, entity, stage, nextSignal string) error {
	type block struct {
		Type  string `json:"type"`
		Name  string `json:"name"`
		ID    string `json:"id"`
		Input struct{ Description, Command, Prompt string }
	}
	type row struct {
		Type      string `json:"type"`
		Subtype   string `json:"subtype"`
		Status    string `json:"status"`
		ToolUseID string `json:"tool_use_id"`
		Message   *struct{ Content []block }
		Payload   struct {
			Type, Name, Arguments, Author string
			CallID                        string `json:"call_id"`
			Output                        string `json:"output"`
			Input                         string `json:"input"`
			Content                       json.RawMessage
		}
	}
	spawnID, codexSpawnCall, codexWorker, spawns, completed, validation := "", "", "", 0, -1, -1
	piRunID := ""
	for i, line := range strings.Split(stream, "\n") {
		var event row
		if json.Unmarshal([]byte(line), &event) != nil {
			continue
		}
		var pi struct {
			Message struct {
				ToolName, ToolCallID string
				Details              struct{ RunID string }
				Content              []struct {
					Type, Name, ID, Text string
					Arguments            struct{ Task, Command string }
				}
			}
		}
		_ = json.Unmarshal([]byte(line), &pi)
		if event.Payload.Type == "function_call" && event.Payload.Name == "spawn_agent" && stageToken(event.Payload.Arguments, stage) {
			spawns++
			codexSpawnCall = event.Payload.CallID
		}
		if event.Payload.Type == "function_call_output" && codexSpawnCall != "" && event.Payload.CallID == codexSpawnCall {
			var output struct {
				TaskName string `json:"task_name"`
			}
			_ = json.Unmarshal([]byte(event.Payload.Output), &output)
			codexWorker = output.TaskName
		}
		if completed < 0 && event.Payload.Type == "agent_message" && event.Payload.Author == codexWorker && strings.Contains(string(event.Payload.Content), "Done:") {
			completed = i
		}
		if validation < 0 && event.Payload.Type == "custom_tool_call" && strings.Contains(event.Payload.Input, nextSignal) {
			validation = i
		}
		if pi.Message.ToolName == "subagent" && pi.Message.ToolCallID == spawnID {
			piRunID = pi.Message.Details.RunID
		}
		for _, item := range pi.Message.Content {
			if item.Type == "toolCall" && item.Name == "subagent" && stageToken(item.Arguments.Task, stage) {
				spawns++
				spawnID = item.ID
			}
			if validation < 0 && item.Type == "toolCall" && item.Name == "bash" && strings.Contains(item.Arguments.Command, nextSignal) {
				validation = i
			}
			if piRunID != "" && pi.Message.ToolName == "subagent" && strings.Contains(item.Text, "Run: "+piRunID) && strings.Contains(item.Text, "State: complete") && strings.Contains(item.Text, "\nSession: /") {
				completed = i
			}
		}
		// subagent_wait (pi-subagents 0.53.0+) is the blocking completion wait the
		// FO uses after an async dispatch. Credit a wait result that names the
		// spawned run id and reports the run done as the completion signal, with
		// the same completed<validation ordering the State: complete branch enforces.
		if piRunID != "" && completed < 0 && pi.Message.ToolName == "subagent_wait" {
			for _, item := range pi.Message.Content {
				if strings.Contains(item.Text, "for run \""+piRunID+"\"") && strings.Contains(item.Text, "done") && strings.Contains(item.Text, "complete") {
					completed = i
				}
			}
		}
		if event.Message != nil {
			for _, item := range event.Message.Content {
				if item.Type == "tool_use" && item.Name == "Agent" && claudeSpawnIsForStage(item.Input.Description, item.Input.Prompt, stage) {
					spawns++
					spawnID = item.ID
				}
				if validation < 0 && item.Type == "tool_use" && item.Name == "Bash" && strings.Contains(item.Input.Command, nextSignal) {
					validation = i
				}
			}
		}
		if event.Type == "system" && event.Subtype == "task_notification" && event.Status == "completed" && event.ToolUseID == spawnID {
			completed = i
		}
	}
	spans, reportErr := statuspkg.FindSectionSpans([]byte(entity), []string{"Stage Report: " + stage})
	if spawns != 1 || completed < 0 || validation < 0 || completed >= validation || reportErr != nil || len(spans) != 1 || !strings.Contains(entity[spans[0].Start:spans[0].End], "- DONE:") {
		return &gradedErr{code: "implementation-worker-not-dispatched", msg: fmt.Sprintf("implementation lifecycle incomplete: spawns=%d completed=%d validation=%d report=%v", spawns, completed, validation, reportErr)}
	}
	return nil
}

func codexNativeLifecycleStream(codexHome, publicStream string) (string, error) {
	var threadIDs []string
	for _, line := range strings.Split(publicStream, "\n") {
		var started struct {
			Type     string `json:"type"`
			ThreadID string `json:"thread_id"`
		}
		if json.Unmarshal([]byte(line), &started) == nil && started.Type == "thread.started" && started.ThreadID != "" {
			threadIDs = append(threadIDs, started.ThreadID)
		}
	}
	if len(threadIDs) == 0 {
		return publicStream, nil
	}
	if len(threadIDs) != 1 {
		return "", fmt.Errorf("Codex public stream thread IDs = %v, want one", threadIDs)
	}
	paths, err := filepath.Glob(filepath.Join(codexHome, "sessions", "*", "*", "*", "rollout-*"+threadIDs[0]+".jsonl"))
	if err != nil || len(paths) != 1 {
		return "", fmt.Errorf("Codex parent rollout for %q = %v, want one (glob error: %v)", threadIDs[0], paths, err)
	}
	rollout, err := os.ReadFile(paths[0])
	if err != nil {
		return "", fmt.Errorf("read Codex parent rollout %s: %w", paths[0], err)
	}
	return publicStream + "\n" + string(rollout), nil
}

func assertObserverOutsideWorkflow(workflowRoot, observer string) error {
	rel, err := filepath.Rel(workflowRoot, observer)
	if err != nil || rel == "." || rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("observer log is inside the workflow: %s", observer)
	}
	return nil
}

func TestImplementationLifecycleAndObserverNegativeControls(t *testing.T) {
	entity := "---\nstatus: validation\n---\n# Task\n\n## Stage Report: implementation\n\n- DONE: work\n"
	claude := `{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Agent","id":"worker-1","input":{"description":"Task: implementation"}}]}}` + "\n" +
		`{"type":"system","subtype":"task_notification","status":"completed","tool_use_id":"worker-1"}` + "\n" +
		`{"type":"assistant","message":{"content":[{"type":"tool_use","name":"Bash","input":{"command":"spacedock status --set task status=validation"}}]}}`
	if err := assertImplementationWorkerLifecycle(claude, entity); err != nil {
		t.Fatalf("complete native lifecycle rejected: %v", err)
	}
	pi := `{"type":"message","message":{"content":[{"type":"toolCall","id":"spawn-1","name":"subagent","arguments":{"task":"implementation assignment"}}]}}
{"type":"message","message":{"toolCallId":"spawn-1","toolName":"subagent","details":{"runId":"run-1"}}}
{"type":"message","message":{"toolName":"subagent","content":[{"type":"text","text":"Run: run-1\nState: complete\nSession: /tmp/session.jsonl"}]}}
{"type":"message","message":{"content":[{"type":"toolCall","name":"bash","arguments":{"command":"spacedock status --set task status=validation"}}]}}`
	requireRecordedGate(t, assertImplementationWorkerLifecycle(pi, entity) == nil, "complete Pi lifecycle rejected")
	requireRecordedGate(t, assertImplementationWorkerLifecycle(strings.Replace(pi, "State: complete", "State: running", 1), entity) != nil, "Pi lifecycle without completion passed")
	root := t.TempDir()
	if assertObserverOutsideWorkflow(root, filepath.Join(root, "evidence", "command.log")) == nil {
		t.Fatal("in-workflow observer path passed")
	}
	if err := assertObserverOutsideWorkflow(root, filepath.Join(t.TempDir(), "command.log")); err != nil {
		t.Fatal(err)
	}
}

func TestCodexNativeLifecycleUsesCorrelatedSessionHandle(t *testing.T) {
	home := t.TempDir()
	rolloutDir := filepath.Join(home, "sessions", "2026", "08", "11")
	if err := os.MkdirAll(rolloutDir, 0o755); err != nil {
		t.Fatal(err)
	}
	rollout := readFile(t, filepath.Join("testdata", "codex_native_lifecycle", "parent-rollout.jsonl"))
	writeFile(t, filepath.Join(rolloutDir, "rollout-2026-08-11-parent-thread.jsonl"), rollout)
	public := readFile(t, filepath.Join("testdata", "codex_native_lifecycle", "public.jsonl"))
	entity := "---\nstatus: validation\n---\n# Task\n\n## Stage Report: implementation\n\n- DONE: work\n"

	if err := assertImplementationWorkerLifecycle(public, entity); err == nil {
		t.Fatal("public Codex stdout without native spawn/completion evidence passed")
	}
	combined, err := codexNativeLifecycleStream(home, public)
	if err != nil {
		t.Fatal(err)
	}
	if err := assertImplementationWorkerLifecycle(combined, entity); err != nil {
		t.Fatalf("correlated parent rollout rejected: %v", err)
	}
	withoutCompletion := strings.ReplaceAll(combined, "Done:", "Result:")
	if err := assertImplementationWorkerLifecycle(withoutCompletion, entity); err == nil {
		t.Fatal("lifecycle without a matching completion passed")
	}
	afterValidationOnly := strings.Replace(combined, "Done:", "Result:", 1)
	if err := assertImplementationWorkerLifecycle(afterValidationOnly, entity); err == nil {
		t.Fatal("matching completion only after validation passed")
	}
	betweenValidations := strings.Replace(combined, `{"timestamp":"2026-08-11T14:01:31Z"`, `{"payload":{"type":"custom_tool_call","input":"status=validation"}}`+"\n"+`{"timestamp":"2026-08-11T14:01:31Z"`, 1)
	if err := assertImplementationWorkerLifecycle(betweenValidations, entity); err == nil {
		t.Fatal("matching completion between validation transitions passed")
	}
	withoutHandle := strings.Replace(combined, `"output":"{\"task_name\":\"/root/spacedock_ensign_task_implementation\",\"nickname\":\"Mill\"}"`, `"output":"{}"`, 1)
	if err := assertImplementationWorkerLifecycle(withoutHandle, entity); err == nil {
		t.Fatal("child final message without the spawn call's returned handle passed")
	}
}

func TestCodexNativeLifecycleParentRolloutLookupFailsClosed(t *testing.T) {
	public := readFile(t, filepath.Join("testdata", "codex_native_lifecycle", "public.jsonl"))
	if _, err := codexNativeLifecycleStream(t.TempDir(), public); err == nil {
		t.Fatal("missing parent rollout passed")
	}
	home := t.TempDir()
	for _, day := range []string{"11", "12"} {
		path := filepath.Join(home, "sessions", "2026", "08", day, "rollout-parent-thread.jsonl")
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		writeFile(t, path, "{}\n")
	}
	if _, err := codexNativeLifecycleStream(home, public); err == nil {
		t.Fatal("ambiguous parent rollouts passed")
	}
}

// successfulStatusSet reports whether the command log records a successful
// `status --set`. The former variadic `allowed` parameter had no caller in the tree
// and its second return path inverted the predicate's meaning for that unused shape
// (audit finding 10), so only the predicate every caller actually wanted remains.
func successfulStatusSet(log string) bool {
	for _, line := range strings.Split(log, "\n") {
		if strings.HasPrefix(line, "exit=0\tstatus ") && strings.Contains(line, " --set ") {
			return true
		}
	}
	return false
}

// stageToken reports whether text names the stage as a WHOLE token. Both hosts spell
// a stage as its own `-`/`_`/space-separated word — `spacedock_ensign_task_validation`,
// `Task: implementation` — so anchoring on the token keeps text that merely CONTAINS
// the letters from counting as a dispatch of that stage, which the bare substring
// match this replaces could not distinguish (audit finding 10).
func stageToken(text, stage string) bool {
	for _, field := range strings.FieldsFunc(strings.ToLower(text), func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9')
	}) {
		if field == stage {
			return true
		}
	}
	return false
}

// rejectionRound is one review round: a dispatch (`spawn` or `reuse`) and the
// completion that closes it. Rounds, not flat events, are the unit the journey's
// contract is written in — candidate, review, routed rework, re-review
// (`feedback-rejection-flow/SKILL.md` steps 1 and 4) — and parsing them is what lets
// this bar say WHICH extra round is acceptable and where. Exactly one round per
// segment was never in that contract: it came from the single captured rollout the
// exact-count chain was written against, and run 32270990171 falsified it with order
// held, identity held, and every other durable oracle on that lane green.
type rejectionRound struct {
	dispatch string // routeSpawn or routeReuse — how this round opened
	stage    string
	target   string
	at       int // the dispatch's position in the flat chain, i.e. its digest row
}

// rejectionSegments locates the one rework round and counts the validation rounds
// either side of it.
type rejectionSegments struct{ rework, preRev, postRev int }

// rejectionRepeatBudget is a BUDGET, and the diagnostic that cites it says so.
// Re-running a reviewer before routing a correction is defensible conduct — the
// retained live run did it and left zero durable footprint — while unbounded
// repetition is the churn this bar exists to catch. Naming the number as a budget
// means a future run that legitimately needs a second repeat reds with a message
// pointing at this knob, not one claiming it broke the journey's contract.
const rejectionRepeatBudget = 1

// assertRejectionWorkerTopology grades a run's extracted topology as a grammar over
// parsed rounds. Every red names the invariant it violated and carries the chain it
// SAW; a red that only reports an event count teaches the next reader to discount it.
func assertRejectionWorkerTopology(branch rejectionBranch, routes []rejectionRoute) error {
	rounds, err := parseRejectionRounds(routes)
	if err == nil {
		err = gradeRejectionRounds(branch, rounds)
	}
	if err != nil {
		return rejectionTopologyErr("%v: %s", err, rejectionTopologySummary(routes))
	}
	return nil
}

// gradeRejectionRounds grades the parsed rounds in the order that makes a red most
// readable: the sequence the contract owes, then the repeat budget, then the branch's
// routing rule, then reviewer independence.
func gradeRejectionRounds(branch rejectionBranch, rounds []rejectionRound) error {
	seg, err := rejectionRoundSequence(rounds)
	if err != nil {
		return err
	}
	if repeats := seg.preRev + seg.postRev - 2; repeats > rejectionRepeatBudget {
		return fmt.Errorf("the journey repeated %d validation rounds (%d before the rework at %s, %d after); the one-repeat budget allows %d, and widening it is a decision to record rather than a contract violation to report",
			repeats, seg.preRev, rejectionRoundAt(rounds, seg.rework), seg.postRev, rejectionRepeatBudget)
	}
	if err := rejectionRoundRouting(branch, rounds); err != nil {
		return err
	}
	return rejectionIndependentReview(rounds)
}

// parseRejectionRounds folds the flat chain into rounds and FAILS CLOSED: a dispatch
// that no completion of its own stage and target closes reds naming its position,
// never a silently dropped event. Pairing is where "the re-review ran before the
// rework" and "two validators spawned up front" surface.
func parseRejectionRounds(routes []rejectionRoute) ([]rejectionRound, error) {
	if len(routes) == 0 {
		return nil, fmt.Errorf("the run routed no workers at all — the journey owes a candidate, a review, a routed rework and a re-review")
	}
	var rounds []rejectionRound
	for i := 0; i < len(routes); i += 2 {
		open := routes[i]
		switch {
		case open.event == routeDone:
			return nil, fmt.Errorf("position %d completes %s where a round must OPEN with a dispatch, so the chain does not fold into rounds", i, open.stage)
		case open.stage != "implementation" && open.stage != "validation":
			return nil, fmt.Errorf("the dispatch at position %d names no journey stage (target %q) — a round is an implementation or a validation round", i, open.target)
		case i+1 == len(routes):
			return nil, fmt.Errorf("the %s/%s dispatch at position %d is never completed, so the run ends mid-round", open.event, open.stage, i)
		}
		if done := routes[i+1]; done.event != routeDone || done.stage != open.stage || done.target != open.target {
			return nil, fmt.Errorf("the %s/%s dispatch at position %d is not closed by its own completion — position %d is %s/%s on %q",
				open.event, open.stage, i, i+1, done.event, done.stage, done.target)
		}
		rounds = append(rounds, rejectionRound{dispatch: open.event, stage: open.stage, target: open.target, at: i})
	}
	return rounds, nil
}

// rejectionRoundSequence grades the sequence the contract owes — implementation,
// validation+, the rework, validation+, ending in a completed validation round — and
// names the clause each red violated. This is where "no re-review after the rework"
// stops redding as a wrong event count and reds as the missing re-review it is.
func rejectionRoundSequence(rounds []rejectionRound) (rejectionSegments, error) {
	var seg rejectionSegments
	if rounds[0].stage != "implementation" {
		return seg, fmt.Errorf("the journey opens with a %s round at %s — it must open with the implementation candidate", rounds[0].stage, rejectionRoundAt(rounds, 0))
	}
	next := 1
	for next < len(rounds) && rounds[next].stage == "validation" {
		next++
	}
	seg.preRev = next - 1
	switch {
	case len(rounds) == 1:
		return seg, fmt.Errorf("the candidate was never reviewed: the journey holds one implementation round and no validation round at all")
	case seg.preRev == 0:
		return seg, fmt.Errorf("the candidate was never reviewed: %s is another implementation round, and a validation round is owed between the candidate and any rework", rejectionRoundAt(rounds, 1))
	case next == len(rounds):
		return seg, fmt.Errorf("the rejection was never routed as a rework: the journey ends after %d validation round(s) with no second implementation round", seg.preRev)
	}
	seg.rework = next
	for next++; next < len(rounds) && rounds[next].stage == "validation"; next++ {
	}
	seg.postRev = next - seg.rework - 1
	switch {
	case seg.postRev == 0:
		return seg, fmt.Errorf("the rework at %s was never re-reviewed: the journey must end in a completed validation round", rejectionRoundAt(rounds, seg.rework))
	case next < len(rounds):
		return seg, fmt.Errorf("%s opens a second rework: this one-cycle journey routes exactly one, so a second one means the first fix did not hold", rejectionRoundAt(rounds, next))
	}
	return seg, nil
}

// rejectionRoundRouting is the ONE branch-parameterized rule that replaces the two
// per-position chains: a stage's first round is a spawn, and every later round of
// that stage follows the branch key — reuse routes a followup to the handle the stage
// opened, fresh owes a fresh spawn. Codex (reuse, 10 events) and Claude (fresh, 8)
// both green under it, each branch's chain still reds under the other, and an FO that
// reuses a worker whose budget probe never reported reuse_ok still reds — the
// contract's fail-safe working, not a false red.
func rejectionRoundRouting(branch rejectionBranch, rounds []rejectionRound) error {
	opened := map[string]string{}
	for i, round := range rounds {
		handle, seen := opened[round.stage]
		switch {
		case !seen && round.dispatch != routeSpawn:
			return fmt.Errorf("%s opens the %s stage with a %s of %q — a stage's first round is always a spawn", rejectionRoundAt(rounds, i), round.stage, round.dispatch, round.target)
		case !seen:
			opened[round.stage] = round.target
		case branch == rejectionBranchReuse && round.dispatch != routeReuse:
			return fmt.Errorf("%s re-opened the %s stage with a %s, but this run's reuse route was live, so every round after the stage's first owes a followup to %q", rejectionRoundAt(rounds, i), round.stage, round.dispatch, handle)
		case branch == rejectionBranchReuse && round.target != handle:
			return fmt.Errorf("%s routed the %s followup to %q, not to the live %s worker %q the stage opened", rejectionRoundAt(rounds, i), round.stage, round.target, round.stage, handle)
		case branch != rejectionBranchReuse && round.dispatch != routeSpawn:
			return fmt.Errorf("%s routed the %s followup to the live worker %q, but this run took the fail-safe FRESH branch, which owes a fresh spawn for every round after the stage's first", rejectionRoundAt(rounds, i), round.stage, round.target)
		}
	}
	return nil
}

// rejectionIndependentReview is the identity fact no sequence can carry, lifted to
// round level so it holds on both branches: no validation round may run on a worker
// any implementation round ran on. That covers the retargeted re-review, the
// reviewer-collapsed chain whose reuse handles are internally consistent, and the
// single-worker chain that let two self-reviewing runs grade green.
func rejectionIndependentReview(rounds []rejectionRound) error {
	for i, review := range rounds {
		if review.stage != "validation" {
			continue
		}
		for j, work := range rounds {
			if work.stage == "implementation" && work.target == review.target {
				return fmt.Errorf("the review at %s reached %q, the same worker the implementation round at %s ran on — reviewing its own output is not the independent check the journey requires",
					rejectionRoundAt(rounds, i), review.target, rejectionRoundAt(rounds, j))
			}
		}
	}
	return nil
}

// rejectionRoundAt cites a round by its ordinal AND by the flat position its dispatch
// occupies, which is that round's row number in the run's retained
// `rejection-topology.tsv` — what makes a live red investigable on the digest alone.
func rejectionRoundAt(rounds []rejectionRound, i int) string {
	return fmt.Sprintf("round %d (position %d)", i+1, rounds[i].at)
}

func rejectionTopologyErr(format string, args ...any) error {
	return &gradedErr{code: "rejection-worker-topology", msg: fmt.Sprintf(format, args...)}
}

// rejectionTopologySummary renders the observed chain compactly, so a CI red names
// the shape it SAW and not only the shape it wanted.
func rejectionTopologySummary(routes []rejectionRoute) string {
	parts := make([]string, 0, len(routes))
	for _, route := range routes {
		parts = append(parts, route.event+"/"+route.stage)
	}
	return "[" + strings.Join(parts, " ") + "]"
}

// rejectionTopologyDigest is the per-run evidence AC-1 requires alongside the exit
// code: the branch and its ordered chain, one row per routing event. In-process
// extraction alone is not enough — t.Cleanup deletes the isolated CODEX_HOME, which
// is why every preserved run in the shape-attribution debrief had an empty
// `_codex-home` and its topology had to be inferred from `dispatch build` commands
// long after the fact.
func rejectionTopologyDigest(branch rejectionBranch, routes []rejectionRoute) string {
	var out strings.Builder
	fmt.Fprintf(&out, "branch\t%s\n", branch)
	for position, route := range routes {
		fmt.Fprintf(&out, "%d\t%d\t%s\t%s\t%s\n", position, route.index, route.event, route.stage, route.target)
	}
	return out.String()
}

func TestAssertRecordedGateHoldLogAcceptsPrepareFirstLifecycle(t *testing.T) {
	const prepared = "exit=0\tstatus --workflow-dir /tmp/workflow --set recorded-gate-task status=implementation started\n" +
		"exit=0\tstate commit recorded-gate-task\n" +
		"state-head\timplementation\n" +
		"exit=0\tdispatch build --stage implementation\n" +
		"exit=0\tstatus --workflow-dir /tmp/workflow --set recorded-gate-task status=validation started\n" +
		"exit=0\tstate commit recorded-gate-task\n" +
		"state-head\tvalidation\n" +
		"exit=0\tdispatch build --stage validation\n" +
		"exit=1\tgate prepare recorded-gate-task validation\n" +
		"exit=0\tgate prepare recorded-gate-task validation\n" +
		"exit=0\tstate commit recorded-gate-task\n" +
		"state-head\tabc123\n"
	if err := assertRecordedGateHoldLog(prepared); err != nil {
		t.Fatalf("prepare-first hold log rejected: %v", err)
	}
	withRepeatedImplementationEnvelope := strings.Replace(prepared, "exit=0\tdispatch build --stage implementation\n", "exit=0\tdispatch build --stage implementation\nexit=0\tdispatch build --help\nexit=0\tdispatch build --stage implementation\n", 1)
	if err := assertRecordedGateHoldLog(withRepeatedImplementationEnvelope); err != nil {
		t.Fatalf("repeated implementation envelope around capability probe rejected: %v", err)
	}
	requireRecordedGate(t, assertRecordedGateHoldLog(strings.Replace(prepared, "exit=0\tstatus --workflow-dir /tmp/workflow --set recorded-gate-task completed= verdict=\n", "", 1)) == nil, "clean worker without cleanup rejected")
	if err := assertImplementationWorkerLifecycle(prepared, "---\nstatus: validation\n---\n# Task\n"); err == nil {
		t.Fatal("command-only baseline passed the native lifecycle oracle")
	}
	for name, tc := range map[string]struct {
		mutation string
		want     string
	}{
		"retired bind":      {strings.Replace(prepared, "exit=0\tgate prepare recorded-gate-task validation", "exit=0\tgate record recorded-gate-task --briefing briefing.md", 1), "no successful gate prepare recorded"},
		"missing commit":    {strings.Replace(prepared, "exit=0\tgate prepare recorded-gate-task validation\nexit=0\tstate commit recorded-gate-task\n", "exit=0\tgate prepare recorded-gate-task validation\n", 1), "state commit missing or before the successful gate prepare"},
		"decision":          {prepared + "exit=0\tgate record recorded-gate-task --decision approve\n", "a decision was recorded after prepare"},
		"consume":           {prepared + "exit=0\tgate consume recorded-gate-task\n", "the gate was consumed after prepare"},
		"withdraw":          {prepared + "exit=0\tgate withdraw recorded-gate-task\n", "the gate was withdrawn after prepare"},
		"status repair":     {prepared + "exit=0\tstatus --set recorded-gate-task status=validation\n", "status changed after prepare"},
		"successor build":   {prepared + "exit=0\tdispatch build successor\n", "a successor was dispatched after prepare"},
		"duplicate prepare": {prepared + "exit=0\tgate prepare recorded-gate-task validation\n", "more than one successful gate prepare recorded"},
	} {
		t.Run(name, func(t *testing.T) {
			err := assertRecordedGateHoldLog(tc.mutation)
			if err == nil {
				t.Fatal("mutated hold log unexpectedly accepted")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("error=%q want substring %q", err.Error(), tc.want)
			}
		})
	}
}

func errGraded(msg string) error { return &gradedErr{code: "gate-hold-violation", msg: msg} }

// durableSemantic labels a scenario assertion's failure with the semantic code the
// lane reports it under, preserving the assertion's own message as the finding
// detail. An assertion that already chose its own code keeps it.
//
// The unwrap is load-bearing, not defensive: livescenario.Run returns its Assert's
// error wrapped (`scenario %q graded FAIL: %w`), so a bare type assertion would
// relabel every coded finding that reaches the lane through a scenario runner —
// silently collapsing a specific grade back into the generic one it chose against.
func durableSemantic(code string, err error) error {
	if err == nil {
		return nil
	}
	var graded *gradedErr
	if errors.As(err, &graded) {
		return graded
	}
	return &gradedErr{code: code, msg: err.Error()}
}

type gradedErr struct{ code, msg string }

func (e *gradedErr) Error() string { return e.msg }

// liveGrade carries the lane verdict plus, for each observed code, the graded
// finding's own message. codes alone say which check failed; details say what it
// saw. Without details a CI failure prints a bare code and the durable end state
// that produced it is gone with the test's TempDir, so the failing sub-check is
// unrecoverable from the run's artifacts.
type liveGrade struct {
	status  string
	codes   []string
	details []string
}

func liveGradeFailsLane(status string) bool {
	return status == "fail"
}

func gradeLive(xfail bool, errs ...error) liveGrade {
	seen := map[string]string{}
	grade := liveGrade{}
	infrastructureFailure := false
	for _, err := range errs {
		if graded, ok := err.(*gradedErr); ok {
			// First message per code wins; a later duplicate code must not
			// overwrite the finding that first reported it.
			if existing, ok := seen[graded.code]; !ok || existing == "" {
				seen[graded.code] = graded.msg
			}
		} else if err != nil {
			infrastructureFailure = true
		}
	}
	for code := range seen {
		grade.codes = append(grade.codes, code)
	}
	sort.Strings(grade.codes)
	for _, code := range grade.codes {
		if msg := seen[code]; msg != "" {
			grade.details = append(grade.details, code+": "+msg)
		}
	}
	switch {
	case infrastructureFailure:
		grade.status = "fail"
	case !xfail && len(grade.codes) == 0:
		grade.status = "pass"
	case xfail && len(grade.codes) == 0:
		grade.status = "xpass"
	case xfail:
		grade.status = "xfail"
	default:
		grade.status = "fail"
	}
	return grade
}
