exec(open('/tmp/spacedock-same-stage-evidence-zz1y/spike.py').read().split("w=ROOT/'self'")[0])
log=json.loads((ROOT/'commands.json').read_text());w=ROOT/'self'
def sd(*a,expect=0):return run([BIN,*a,'--workflow-dir',str(w)],w,expect)
old=(w/'task/review/plan/briefing-1/index.json').read_bytes(); frozen=(w/'task/frozen-input.txt').read_bytes()
(w/'task/plan.md').write_bytes(frozen)
with (w/'task/index.md').open('a') as f:f.write('\n## Stage Report: plan (cycle 2)\n- DONE: Correct plan against frozen input and commit stage report\n  Manual CLI spike operator corrected the plan; no external execution.\n### Summary\nKEEP A and DELETE B match frozen input.\n')
run(['git','add','task'],w);run(['git','commit','-qm','correct plan and commit completion report'],w)
sd('gate','record','task','--decision','approve','--actor','person:captain',expect=1)
sd('gate','prepare','task','--question','Approve corrected local plan?','--artifact',str(w/'task/plan.md'),'--summary','corrected plan')
sd('state','commit','task');sd('status','--next','--json')
assert old==(w/'task/review/plan/briefing-1/index.json').read_bytes();assert frozen==(w/'task/frozen-input.txt').read_bytes()
run(['git','log','--oneline'],w);run(['git','status','--short'],w)
(ROOT/'assertions.txt').write_text('PASS: frozen input and old briefing bytes unchanged; corrected plan equals independently seeded frozen input; old closed revise refused approve and consume; exactly one fresh open gate shown by status; no new approve or consume called. Operator completion, not live subagent proof.\n')
# Shipped advisory-round path, copied fixture with genuine public CLI parser.
w=ROOT/'advisory';w.mkdir(exist_ok=True)
(w/'README.md').write_text('---\nid-style: slug\nstages:\n  states:\n    - name: implementation\n      initial: true\n---\n# Advisory implementation round\n')
(w/'task/inputs').mkdir(parents=True,exist_ok=True)
(w/'task/index.md').write_text('---\nid: task\nstatus: implementation\ntitle: Advisory task\n---\n# Task\n')
import shutil
src=pathlib.Path('/tmp/spacedock-same-stage-ideation-zz1y/internal/gates/testdata/advisory-round')
for name in ['briefing.json','briefing.review.jsonl']:shutil.copy(src/name,w/'task/inputs'/name)
shutil.copy(src/'candidate.patch',w/'task/candidate.patch')
for a in [['git','init','-q'],['git','config','user.email','spike@example.invalid'],['git','config','user.name','Ideation spike'],['git','add','.'],['git','commit','-qm','seed advisory fixture']]:run(a,w)
full=(w/'task/inputs/briefing.review.jsonl').read_text();(w/'task/inputs/incomplete.jsonl').write_text('\n'.join(full.splitlines()[:3])+'\n')
sd('gate','record','task','--round','implementation/1','--briefing',str(w/'task/inputs/briefing.json'),'--log',str(w/'task/inputs/missing.jsonl'),expect=1)
sd('gate','record','task','--round','implementation/1','--briefing',str(w/'task/inputs/briefing.json'),'--log',str(w/'task/inputs/incomplete.jsonl'),expect=1)
sd('gate','record','task','--round','implementation/1','--briefing',str(w/'task/inputs/briefing.json'),'--log',str(w/'task/inputs/briefing.review.jsonl'))
sd('state','commit','task');sd('status','--validate');run(['git','log','--oneline'],w)
